from easygui import*
from time import*
from pyautogui import*
from turtle import*
from random import choice

filenames=['troll.txt','bruh.txt','huhuhuhuh.txt','yowatthesigma.txt','sigmadeez.txt','whatthebruhdeezsigmafanumtax.txt','fanumtaxyomoma.txt','fanumtax.txt','skibidisigmafanumtaxultimate600gyattpower.txt','skibidirizzler.txt','skibidi.txt','professionalfanumtaxrizzler.txt','sigmafanumtaxrizzlerbrubruBRUHHHHHHH.txt','IDONTKNOWWHATIAMDOING.txt','0110001101101111011011010111000001110101011101000110010101110010001000000110100101101110011001100110010101100011011101000110010101100100.txt','nggyu.txt','RICKROLLSIGMA.txt','memetroll.txt','SIGMASIGMASIGMASIGMASIGMASIGMASIGMASIGMASIGMASIGMAHUHUHHHFIGBRUHHHH.txt']

msgbox("WARNING: this program can close tabs! Are you shure to do this? recommend making a new browser to test!", title="NOTE!", ok_button="OK")
msgbox("And also this will only work in Windows 9-11!", title="NOTE!", ok_button="Accept")
sleep(3)
hotkey("Alt", "F4")
sleep(1)
msgbox("Okay...", title="", ok_button="Continue speech")
msgbox("So now I have more space.", title="", ok_button="Continue speech")
msgbox("Oh...and hello!", title="", ok_button="Hi")
msgbox("What do you want to do do?", title="", ok_button="I want to learn something")
msgbox("Okay...",title="",ok_button="...")
msgbox("So you want to learn something...",title="",ok_button="Yes...")
msgbox("...disturbing",title="",ok_button="No no!")
msgbox("Okay...",title="",ok_button="...")
msgbox("...So here's a disturbing fact!",title="",ok_button="I SAID NO!")
msgbox("Did you know that during mummification, they remove the brain?",title="",ok_button="STOP ITTT!!!")
msgbox("And they store the organs in a container?",title="",ok_button="EWWWWWWWWWWWWWWWWW!!!!!!!")
msgbox("And did you know...",title="",ok_button="*FAINTS*")
sleep(5)
bgcolor("black")
title("")
sleep(1)
msgbox("Are you okay?", title="",ok_button=".......")
msgbox("Hey!",title="",ok_button="Wha...")
msgbox("  ", ok_button="Wait...Is this all a dream?")
msgbox("Okay...Now what do you want to do?", ok_button="Play a game..?")
msgbox("Okay!",ok_button="...")
msgbox("So let's play Minecraft!",ok_button="YESSS!!!")
sleep(1)
bye()
msgbox("Computer malfunctioning...",ok_button="wait..")
msgbox("Downloading trolls...",ok_button="huh?")
msgbox("Trojan sucessfully entered computer",ok_button="Uh OHHHHHH...")
for i in range(1000):
    random_f=choice(filenames)
    with open(random_f,'w') as file:
        file.write("trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL trolllolololol LOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL")
sleep(2)
msgbox("""We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy

I just wanna tell you how I'm feeling
Gotta make you understand

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

We've known each other for so long
Your heart's been aching, but
You're too shy to say it
Inside, we both know what's been going on
We know the game and we're gonna play it

And if you ask me how I'm feeling
Don't tell me you're too blind to see

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

Never gonna give, never gonna give
Never gonna give, never gonna give

We've known each other for so long
Your heart's been aching, but
You're too shy to say it
Inside, we both know what's been going on
We know the game and we're gonna play it

I just wanna tell you how I'm feeling
Gotta make you understand

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you""", ok_button="HAHHHHHH???????????")
